services:
  - type: web
    name: ardito-stackfordevs-api
    env: docker
    dockerfilePath: ./Dockerfile
    envVars:
      - key: NODE_ENV
        value: production
      - key: STACKFORDEVS_TENANT_ID
        sync: false
      - key: STACKFORDEVS_PROJECT_ID
        sync: false
      - key: STACKFORDEVS_API_KEY
        sync: false
      - key: STACKFORDEVS_SECRET_API_KEY
        sync: false
      - key: STACKFORDEVS_AUTH_API_URL
        value: https://auth.stackfordevs.com
      - key: STACKFORDEVS_NOTIFICATIONS_API_URL
        value: https://notifications.stackfordevs.com
      - key: STACKFORDEVS_MAILER_API_URL
        value: https://mailer.stackfordevs.com
      - key: STACKFORDEVS_LLM_API_URL
        value: https://llm.stackfordevs.com
      - key: STACKFORDEVS_CMS_API_URL
        value: https://cms.stackfordevs.com
      - key: STACKFORDEVS_BILLING_API_URL
        value: https://billing.stackfordevs.com
