services:
  - type: web
    name: ardito-stackfordevs-api
    env: docker
    dockerfilePath: ./Dockerfile
    envVars:
      - key: NODE_ENV
        value: production
      - key: NEXT_PUBLIC_TENANT_ID
        sync: false
      - key: NEXT_PUBLIC_PROJECT_ID
        sync: false
      - key: NEXT_PUBLIC_API_KEY
        sync: false
      - key: NEXT_PUBLIC_SECRET_API_KEY
        sync: false
      - key: NEXT_PUBLIC_AUTH_API_URL
        value: https://auth.stackfordevs.com
      - key: NEXT_PUBLIC_NOTIFICATIONS_API_URL
        value: https://notifications.stackfordevs.com
      - key: NEXT_PUBLIC_MAILER_API_URL
        value: https://mailer.stackfordevs.com
      - key: NEXT_PUBLIC_LLM_API_URL
        value: https://llm.stackfordevs.com
      - key: NEXT_PUBLIC_CMS_API_URL
        value: https://cms.stackfordevs.com
      - key: NEXT_PUBLIC_BILLING_API_URL
        value: https://billing.stackfordevs.com
